import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Gameview from '../components/game.view'
import { useSupabaseClient } from '@supabase/auth-helpers-react'
import { useUser } from '@/utils/useUser'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const supabase = useSupabaseClient()
  const { userDetails } = useUser()

  return (
    <>
      <Head>
        <title>Hacker Cool!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          {
            userDetails && <button style={{ display: 'flex', width: 100, height: 50, justifyContent: 'center', alignItems: 'center', textAlign: 'center' }} onClick={() => supabase.auth.signOut()}>SignOut</button>
          }
          <p>
            Hacker Cool !
          </p>
          {
            userDetails && <div className={styles.avatar}>
              <img width={70} height={70} src={userDetails.avatar_url} alt="" />
            </div>
          }
        </div>
        <div className={styles.center}>
          <Gameview />
        </div>
      </main>
    </>
  )
}
